<?php $page = $_GET['page'] ?? 'dashboard'; $titles=['dashboard'=>'Dashboard','barang'=>'Data Barang','kategori'=>'Kategori','lokasi'=>'Lokasi Storage','transaksi'=>'Transaksi','riwayat'=>'Riwayat Transaksi','scan'=>'Scan QR Code','kunjungan'=>'Aktivitas Ruangan','room_logs'=>'Log Pengunjung Ruangan','profil'=>'Profil Saya']; ?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($titles[$page]??'STOKLY')?> | STOKLY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?=url('assets/style.css')?>" rel="stylesheet"></head><body>
<nav class="navbar navbar-dark bg-primary fixed-top d-lg-none"><div class="container-fluid"><a class="navbar-brand fw-bold" href="<?=url('index.php')?>"><span class="brand-strong">STOK</span><span class="brand-light">LY</span></a><button type="button" class="navbar-toggler" id="mobile-menu-toggle" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Buka menu"><span class="navbar-toggler-icon"></span></button></div></nav>
<aside class="offcanvas-lg offcanvas-start sidebar" tabindex="-1" id="sidebar"><div class="offcanvas-header border-bottom"><strong><span class="brand-strong">STOK</span><span class="brand-light">LY</span></strong><button type="button" class="btn-close d-lg-none" data-bs-dismiss="offcanvas" aria-label="Tutup menu"></button></div><div class="p-3"><a class="brand d-none d-lg-block mb-4" href="<?=url('index.php')?>">▣ <span class="brand-strong">STOK</span><span class="brand-light">LY</span></a><small class="text-uppercase text-secondary">Menu</small><nav class="nav flex-column mt-2">
<?php if(!logged_in()||has_permission('dashboard_view')):?><a class="nav-link <?= $page==='dashboard'?'active':'' ?>" href="<?=url('index.php')?>">▦ Dashboard</a><?php endif;?>
<?php if(!logged_in()||has_permission('barang_view')):?><a class="nav-link <?= $page==='barang'?'active':'' ?>" href="<?=url('index.php?page=barang')?>">▣ Data Barang</a><?php endif;?>
<?php if(logged_in()&&has_permission('transaction_manage')):?><a class="nav-link <?= $page==='transaksi'?'active':'' ?>" href="<?=url('index.php?page=transaksi')?>">⇄ Transaksi</a><?php endif;?>
<?php if(logged_in()&&has_permission('history_view')):?><a class="nav-link <?= $page==='riwayat'?'active':'' ?>" href="<?=url('index.php?page=riwayat')?>">☷ Riwayat</a><?php endif;?>
<?php if(logged_in()&&has_permission('scan_view')):?><a class="nav-link <?= $page==='scan'?'active':'' ?>" href="<?=url('index.php?page=scan')?>">▣ Scan QR Code</a><?php endif;?>
<?php if(logged_in()&&has_permission('room_log_view')):?><a class="nav-link <?= in_array($page,['kunjungan','room_logs'],true)?'active':'' ?>" href="<?=url('room_logs.php')?>">◉ Aktivitas Ruangan</a><?php endif;?>
<?php if(is_admin()):?><hr><a class="nav-link" href="<?=url('members.php')?>">Kelola Member & Admin</a><?php endif;?>
<?php if(logged_in()&&(has_permission('category_manage')||has_permission('location_manage'))):?><hr><?php if(has_permission('category_manage')):?><a class="nav-link <?= $page==='kategori'?'active':'' ?>" href="<?=url('index.php?page=kategori')?>">◈ Kategori</a><?php endif;?><?php if(has_permission('location_manage')):?><a class="nav-link <?= $page==='lokasi'?'active':'' ?>" href="<?=url('index.php?page=lokasi')?>">⌖ Lokasi Storage</a><?php endif;?><?php endif;?></nav></div></aside>
<main class="main"><header class="topbar"><div><h4 class="mb-0"><?=e($titles[$page]??'Storage QR')?></h4><small class="text-secondary"><?=logged_in()?'Kelola storage dengan mudah':'Mode Guest - hanya melihat data'?></small></div><?php if(logged_in()):?><div class="dropdown"><button class="btn btn-light border dropdown-toggle" data-bs-toggle="dropdown">👤 <?=e($_SESSION['user']['nama'])?></button><ul class="dropdown-menu dropdown-menu-end"><li><span class="dropdown-item-text text-secondary small"><?=e(role_label())?></span></li><li><a class="dropdown-item" href="<?=url('logout.php')?>">Keluar</a></li></ul></div><?php else:?><a class="btn btn-primary" href="<?=url('login.php')?>">Masuk / Daftar</a><?php endif;?></header><div class="container-fluid py-4"><?php show_flash();?><script>document.addEventListener('DOMContentLoaded',()=>{const heading=[...document.querySelectorAll('h5')].find(x=>x.textContent.trim()==='Aktivitas storage');if(!heading)return;const cardBody=heading.closest('.card-body');const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));const refresh=()=>fetch('activity_feed.php',{cache:'no-store'}).then(response=>response.json()).then(data=>{while(heading.nextElementSibling)heading.nextElementSibling.remove();data.activities.forEach(item=>{const color=item.jenis==='masuk'?'success':'warning';cardBody.insertAdjacentHTML('beforeend','<div class="storage-activity-item border-bottom py-2"><b>'+esc(item.nama)+'</b> <span class="badge text-bg-'+color+'">'+esc(item.jenis)+'</span><br><small class="text-secondary">'+item.jumlah+' unit oleh '+esc(item.user)+' · '+esc(item.waktu)+'</small></div>');});}).catch(()=>{});refresh();setInterval(refresh,5000);});</script>
