<?php
require_once __DIR__.'/bootstrap.php'; permission_only('reports_view');
$periode=$_GET['periode']??'harian';if(!in_array($periode,['harian','bulanan'],true))$periode='harian';
$tanggal=$_GET['tanggal']??date('Y-m-d');$bulan=$_GET['bulan']??date('Y-m');
if($periode==='harian'){$label='LAPORAN HARIAN';$rentang=$tanggal;$sql='SELECT t.*,CONCAT(DATE_FORMAT(t.tanggal,"%Y-%m-%d")," ",DATE_FORMAT(t.created_at,"%H:%i:%s")) tanggal,b.kode,b.nama,b.satuan,u.nama user FROM transaksi t JOIN barang b ON b.id=t.barang_id JOIN users u ON u.id=t.user_id WHERE t.tanggal=? ORDER BY t.id';$params=[$tanggal];}
else{$label='LAPORAN BULANAN';$rentang=date('F Y',strtotime($bulan.'-01'));$sql='SELECT t.*,CONCAT(DATE_FORMAT(t.tanggal,"%Y-%m-%d")," ",DATE_FORMAT(t.created_at,"%H:%i:%s")) tanggal,b.kode,b.nama,b.satuan,u.nama user FROM transaksi t JOIN barang b ON b.id=t.barang_id JOIN users u ON u.id=t.user_id WHERE DATE_FORMAT(t.tanggal,"%Y-%m")=? ORDER BY t.tanggal,t.id';$params=[$bulan];}
$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll(PDO::FETCH_ASSOC);$masuk=0;$keluar=0;foreach($rows as $r){if($r['jenis']==='masuk')$masuk+=(int)$r['jumlah'];else $keluar+=(int)$r['jumlah'];}
function pdf_clean($text,$limit=80){$text=strip_tags((string)$text);$text=preg_replace('/\s+/',' ',$text);$text=iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',$text)?:'';return mb_strlen($text)>$limit?mb_substr($text,0,$limit-3).'...':$text;}
function pdf_text($x,$y,$text,$size=10,$bold=false){$font=$bold?'F2':'F1';$text=str_replace(['StorageQR','Storage QR'],'STOKLY',(string)$text);$text=str_replace(['\\','(',')'],['\\\\','\\(', '\\)'],pdf_clean($text));return "BT /$font $size Tf 1 0 0 1 $x $y Tm ($text) Tj ET\n";}
function pdf_line($x1,$y1,$x2,$y2){return "$x1 $y1 m $x2 $y2 l S\n";}
function pdf_document($pages){$objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',4=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];$ids=[];$next=5;foreach($pages as $content){$page=$next++;$stream=$next++;$ids[]=$page;$objects[$page]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents '.$stream.' 0 R >>';$objects[$stream]='<< /Length '.strlen($content).' >>' . "\nstream\n$content\nendstream";}$objects[2]='<< /Type /Pages /Kids ['.implode(' ',array_map(fn($id)=>$id.' 0 R',$ids)).'] /Count '.count($ids).' >>';ksort($objects);$pdf="%PDF-1.4\n";$offsets=[0];foreach($objects as $id=>$object){$offsets[$id]=strlen($pdf);$pdf.=$id." 0 obj\n$object\nendobj\n";}$xref=strlen($pdf);$pdf.='xref'."\n0 ".(max(array_keys($objects))+1)."\n0000000000 65535 f \n";for($i=1;$i<=max(array_keys($objects));$i++)$pdf.=sprintf('%010d 00000 n ',$offsets[$i]??0)."\n";$pdf.="trailer\n<< /Size ".(max(array_keys($objects))+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";return $pdf;}
$pages=[];$newPage=function()use(&$pages,$label,$rentang,$masuk,$keluar){$c="0.15 0.39 0.92 rg\n".pdf_text(40,800,'StorageQR - Manajemen Storage / Gudang',16,true)."0 g\n".pdf_text(40,775,'INVOICE '.$label,14,true).pdf_text(40,758,'Periode: '.$rentang,10).pdf_text(40,743,'Dicetak: '.date('d-m-Y H:i').' | Oleh: '.$_SESSION['user']['nama'],9).pdf_line(40,732,555,732).pdf_text(40,712,'Total transaksi: '.count($GLOBALS['rows']).' | Barang masuk: '.$masuk.' | Barang keluar: '.$keluar,10,true)."0.90 g\n40 675 515 18 re f\n0 g\n".pdf_text(44,681,'No',8,true).pdf_text(72,681,'Tanggal',8,true).pdf_text(130,681,'Kode / Barang',8,true).pdf_text(292,681,'Jenis',8,true).pdf_text(348,681,'Jumlah',8,true).pdf_text(407,681,'User',8,true).pdf_text(470,681,'Keterangan',8,true);$pages[]=['content'=>$c,'y'=>657];};$newPage();
foreach($rows as $i=>$r){$last=count($pages)-1;if($pages[$last]['y']<85)$newPage();$last=count($pages)-1;$y=$pages[$last]['y'];$c=pdf_text(44,$y,(string)($i+1),8).pdf_text(72,$y,$r['tanggal'],8).pdf_text(130,$y,$r['kode'],8,true).pdf_text(130,$y-10,$r['nama'],8).pdf_text(292,$y,ucfirst($r['jenis']),8).pdf_text(348,$y,$r['jumlah'].' '.$r['satuan'],8).pdf_text(407,$y,$r['user'],8).pdf_text(470,$y,pdf_clean($r['keterangan']?:'-',18),8).pdf_line(40,$y-17,555,$y-17);$pages[$last]['content'].=$c;$pages[$last]['y']-=25;}
foreach($pages as &$page){$page['content'].=pdf_text(40,42,'Dokumen dibuat otomatis oleh StorageQR.',8).pdf_text(405,42,'Mengetahui, __________________',8);}$binary=pdf_document(array_column($pages,'content'));$filename='invoice-storage-'.($periode==='harian'?$tanggal:$bulan).'.pdf';header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Content-Length: '.strlen($binary));header('Cache-Control: private, max-age=0');echo $binary;exit;
