<?php
require_once __DIR__.'/bootstrap.php';
if(logged_in()){header('Location: '.url('index.php'));exit;}
if(is_post()){
    verify_csrf();
    $nama=trim($_POST['nama']??'');$username=trim($_POST['username']??'');$password=$_POST['password']??'';$konfirmasi=$_POST['konfirmasi']??'';
    if(strlen($nama)<3||!preg_match('/^[a-zA-Z0-9_.-]{3,50}$/',$username)) $error='Nama minimal 3 karakter dan username hanya boleh huruf, angka, titik, garis bawah, atau minus.';
    elseif(!password_is_strong($password)) $error='Password minimal 8 karakter dan harus berisi huruf besar, huruf kecil, serta angka.';
    elseif($password!==$konfirmasi) $error='Konfirmasi password tidak sama.';
    else {try{$s=$pdo->prepare('INSERT INTO users(nama,username,password,role) VALUES(?,?,?,"user")');$s->execute([$nama,$username,password_hash($password,PASSWORD_DEFAULT)]);$newId=(int)$pdo->lastInsertId();$permissionInsert=$pdo->prepare('INSERT INTO user_permissions(user_id,permission) VALUES(?,?)');foreach(['dashboard_view','barang_view','units_view'] as $permission)$permissionInsert->execute([$newId,$permission]);flash('success','Pendaftaran berhasil. Silakan masuk sebagai Member.');header('Location: '.url('login.php'));exit;}catch(PDOException $e){$error='Username sudah digunakan. Silakan pilih username lain.';}}
}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daftar Member | StorageQR</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container"><div class="row justify-content-center align-items-center min-vh-100"><div class="col-md-6 col-lg-5"><div class="card shadow-sm border-0"><div class="card-body p-4 p-md-5"><h2 class="text-primary fw-bold">Daftar Member</h2><p class="text-secondary">Buat akun untuk mengakses data storage.</p><?php if(!empty($error)):?><div class="alert alert-danger"><?=e($error)?></div><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="mb-3"><label class="form-label">Nama lengkap</label><input class="form-control" name="nama" required value="<?=e($_POST['nama']??'')?>"></div><div class="mb-3"><label class="form-label">Username</label><input class="form-control" name="username" required value="<?=e($_POST['username']??'')?>"></div><div class="mb-3"><label class="form-label">Password</label><input type="password" class="form-control" name="password" minlength="8" required></div><div class="mb-4"><label class="form-label">Konfirmasi password</label><input type="password" class="form-control" name="konfirmasi" minlength="8" required></div><button class="btn btn-primary w-100">Daftar sebagai Member</button></form><p class="text-center mt-3 mb-0">Sudah punya akun? <a href="<?=url('login.php')?>">Masuk</a></p></div></div></div></div></div></body></html>
